import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {process.env.AUTH_DISABLED === "1" && (
          <div className="bg-destructive text-destructive-foreground px-4 py-1.5 text-center text-xs font-medium">
            AUTH_DISABLED=1 — sign-in is bypassed, every request uses one shared dev org. Never
            deploy like this.
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
